### ISSUE TITLE
Flatten array with nulls

### ISSUE THREAD

**Issue by dy** [glo-js/flatten-vertex-data#2]
```js
flatten([,NaN,undefined,null]) // [NaN, NaN, NaN, 0]
```

That does not seem right that `null`s get converted to `0` instead of `NaN`. First, `JSON.stringify(NaN) === "null"`, meaning that if we flatten JSON data with `null`s it gets misinterpreted. Second, `null` is not a number.

**Comment by dy** [comment]
@mattdesl will you accept a PR?

**Comment by mattdesl** [comment]
Hey, sorry for the delay. Yes I will accept a PR if it has tests. Thanks.
